<?php
/**
 * Created by PhpStorm.
 * User: Vassya
 * Date: 29.11.2014
 * Time: 19:55
 */
?>
<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'leagues', 'action' => 'add'), 'default'); ?>" id="menu" >Add Leagues</a>
<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'leagues', 'action' => 'delete'), 'default'); ?>" id="menu" >Delete Leagues</a>
<?php echo $this->formSearch; ?>
<?php
if (count($this->leagues)) {
    ?>
    <table>
        <tr>
            <th><a href="
                    <?php echo $this->url(array('module' => 'default', 'controller' => 'leagues', 'action' => 'index'), 'default')
                    . '?sort=league_name'; ?>" id="sort" >League Name</a></th>
            <th><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'leagues', 'action' => 'index'), 'default')
                    . '?sort=country_name'; ?>" id="sort" >Country</a></th>
            <th><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'leagues', 'action' => 'index'), 'default')
                    . '?sort=uefa_rating'; ?>" id="sort" >UEFA Rating</a></th>
            <th><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'leagues', 'action' => 'index'), 'default')
                    . '?sort=president_name'; ?>" id="sort" >President</a></th>
        </tr>
        <?php
        foreach ($this->leagues as $l) {
            echo "<tr>";
            echo "<td>" . $l->league_name . "</td>";
            echo "<td>" . $l->country_name . "</td>";
            echo "<td>" . $l->uefa_rating . "</td>";
            echo "<td>" . $l->president_name . "</td>";
            echo "</tr>";
        }
        ?>
    </table>
<?php
}else{
    echo "<p>No Leagues</p>";
}
