<?php
require('../connect_to_db.php');
require('../../model/clubs.php');
require('../../model/leagues.php');
require('../../model/trophies.php');
require('../../model/stadiums.php');
require('output.php');
require('input.php');
?>