<?php
/**
 * Created by PhpStorm.
 * User: Vassya
 * Date: 29.11.2014
 * Time: 20:21
 */
?>
<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'stadiums', 'action' => 'add'), 'default'); ?>" id="menu" >Add Stadiums</a>
<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'stadiums', 'action' => 'delete'), 'default'); ?>" id="menu" >Delete Stadiums</a>
<?= $this->formSearch; ?>
<?php
    if (count($this->stadiums)) {
    ?>
    <table>
        <tr>
            <th><a href="
                    <?php echo $this->url(array('module' => 'default', 'controller' => 'stadiums', 'action' => 'index'), 'default')
                    . '?sort=name'; ?>" id="sort" >Stadium Name</a></th>
            <th><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'stadiums', 'action' => 'index'), 'default')
                    . '?sort=year'; ?>" id="sort" >Year</a></th>
            <th><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'stadiums', 'action' => 'index'), 'default')
                    . '?sort=capacity'; ?>" id="sort" >Capacity</a></th>
        </tr>
        <?php
        foreach ($this->stadiums as $s) {
            echo "<tr>";
            echo "<td>" . $s->name . "</td>";
            echo "<td>" . $s->year . "</td>";
            echo "<td>" . $s->capacity . "</td>";
            echo "</tr>";
        }
        ?>
    </table>
<?php
}else{
    echo "<p>No Stadiums</p>";
}
